# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-db
spec:
  selector:
    matchLabels:
      app: psql-db
  replicas: 1
  template:
    metadata:
      labels:
        app: psql-db
    spec:
      containers:
        - name: psql-db
          image: postgres:13
          ports:
            - containerPort: 5432
              name: "postgres"
          env:
            - name: POSTGRES_DB
              value: datascore
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: root
